Use USERPROFILE dir to store ccache on Windows.
hendrikmuhs/ccache-action pull request #82
Opened 2022-06-09 04:37 UTC by nmoinvaz

See #80.

2022-06-09 13:47 UTC, jonashaag requested changes

2022-06-09 13:47 UTC, jonashaag commented on src/restore.ts
> +    `${process.env.USERPROFILE}\\.cargo\\bin`,
```suggestion
    // TODO find a better place
    `${process.env.USERPROFILE}\\.cargo\\bin`,
```

Still a bad place.

2022-06-09 13:47 UTC, jonashaag commented on src/restore.ts
> +    `${process.env.USERPROFILE}\\.cargo\\bin`,
```suggestion
    // TODO find a better place
    `${process.env.USERPROFILE}\\.cargo\\bin`,
```

2022-06-09 16:32 UTC, jonashaag approved these changes

2022-06-09 16:47 UTC, nmoinvaz commented
It looks like PATH environment variable needs to be set.

2022-06-09 17:00 UTC, jonashaag commented
Is this on a self-hosted runner or on a GitHub runner? On GitHub I would expect `.cargo` to be in `PATH`. We can also find another place to put the file, or use another installation method like `choco` (I don't know anything about `choco` though)

2022-06-09 17:08 UTC, nmoinvaz commented
Yes, it is on a self-hosted runner. `choco` is a popular package manager for Windows that is also pre-installed on GitHub's runners. You just run `choco install ccache` and it will install `ccache` and put it in the `PATH` - similar to `brew install ccache` etc.

2022-07-20 18:56 UTC, merged

2022-07-20 19:15 UTC, nmoinvaz commented
No worries. I didn't push hard for it because I still think `choco` is probably the way to go on Windows.